language: go

services:
- redis-server

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/adjust/bufio
  - go get github.com/adjust/check
  - mkdir -p $HOME/gopath/src/gopkg.in
  - ln -s `pwd` $HOME/gopath/src/github.com/adjust/redis

before_script:
  - redis-server testdata/sentinel.conf --sentinel &
